[package]
name = "hinafont"
version = "0.2.0"
authors = ["Chun-Kwong Wong <chunkwong.wong@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
